name: Android Master CI

on:
  push:
    branches:  
      - 'master' 
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Generate apk.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: navigate to code folder
      run: cd Code
    - name: Build debug APK
      run:  Code/gradlew build --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
